export class AuditInvalidFilterError extends Error { constructor() { super("AUDIT_INVALID_FILTER"); this.name = "AuditInvalidFilterError"; } }
export type AuditFilters = { query?: string; module?: string; action?: string; entityType?: string; entityId?: string; actorId?: string; actorRole?: string; severity?: string; origin?: string; dateFrom?: string; dateTo?: string; page?: number; pageSize?: number };
function text(params: URLSearchParams, key: string) { const value = params.get(key)?.trim(); return value || undefined; }
function positive(params: URLSearchParams, key: string) { const raw = params.get(key); if (!raw) return undefined; const value = Number(raw); if (!Number.isInteger(value) || value < 1) throw new AuditInvalidFilterError(); return value; }
function date(params: URLSearchParams, key: string) { const value = text(params, key); if (value && !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new AuditInvalidFilterError(); return value; }
export function parseAuditFilters(params: URLSearchParams): AuditFilters { const dateFrom = date(params, "dateFrom"); const dateTo = date(params, "dateTo"); if (dateFrom && dateTo && dateFrom > dateTo) throw new AuditInvalidFilterError(); return { query: text(params, "query") ?? text(params, "q"), module: text(params, "module"), action: text(params, "action"), entityType: text(params, "entityType"), entityId: text(params, "entityId"), actorId: text(params, "actorId"), actorRole: text(params, "actorRole"), severity: text(params, "severity"), origin: text(params, "origin"), dateFrom, dateTo, page: positive(params, "page"), pageSize: positive(params, "pageSize") }; }
export function auditSeverity(action: string, stored?: string | null): "INFO" | "WARNING" | "CRITICAL" { if (stored === "CRITICAL" || stored === "WARNING") return stored; if (/delete|role|permission|publish|refund|failed|denied|blocked|archive/i.test(action)) return /failed|denied|blocked/i.test(action) ? "WARNING" : "CRITICAL"; return "INFO"; }
export type AuditListItem = { id: string; createdAt: Date; actorId: string | null; actorRole: string | null; action: string; module: string; entityType: string; entityId: string; before: Record<string, unknown> | null; after: Record<string, unknown> | null; origin: string | null; requestId: string | null; correlationId: string | null; metadata: Record<string, unknown> | null; severity: "INFO" | "WARNING" | "CRITICAL" };
export type AuditPageResponse = { items: AuditListItem[]; page: number; pageSize: number; totalItems: number; totalPages: number; metrics: { total: number; critical: number; actors: number; failedAttempts: number | null }; facets: { modules: string[]; actions: string[]; entityTypes: string[]; severities: string[] } };
