import { and, asc, count, countDistinct, desc, eq, gte, ilike, isNotNull, lt, or, type SQL } from "drizzle-orm";
import { getDb } from "@/db";
import { auditLogs } from "@/db/schema";
import { auditSeverity, type AuditFilters, type AuditListItem, type AuditPageResponse } from "@/lib/audit-contract";
const defaultPageSize = 25; const maxPageSize = 100;
function dayStart(value: string) { return new Date(`${value}T00:00:00-05:00`); } function dayAfter(value: string) { return new Date(dayStart(value).getTime() + 86_400_000); } function n(value: unknown) { return Number(value ?? 0); }
function whereAudit(filters: AuditFilters) { const conditions: SQL[] = []; if (filters.query) { const pattern = `%${filters.query}%`; conditions.push(or(ilike(auditLogs.id, pattern), ilike(auditLogs.action, pattern), ilike(auditLogs.entityType, pattern), ilike(auditLogs.entityId, pattern), ilike(auditLogs.actorId, pattern), ilike(auditLogs.module, pattern), ilike(auditLogs.origin, pattern))!); } if (filters.module) conditions.push(eq(auditLogs.module, filters.module)); if (filters.action) conditions.push(eq(auditLogs.action, filters.action)); if (filters.entityType) conditions.push(eq(auditLogs.entityType, filters.entityType)); if (filters.entityId) conditions.push(eq(auditLogs.entityId, filters.entityId)); if (filters.actorId) conditions.push(eq(auditLogs.actorId, filters.actorId)); if (filters.actorRole) conditions.push(eq(auditLogs.actorRole, filters.actorRole)); if (filters.severity) conditions.push(eq(auditLogs.severity, filters.severity)); if (filters.origin) conditions.push(eq(auditLogs.origin, filters.origin)); if (filters.dateFrom) conditions.push(gte(auditLogs.createdAt, dayStart(filters.dateFrom))); if (filters.dateTo) conditions.push(lt(auditLogs.createdAt, dayAfter(filters.dateTo))); return conditions.length ? and(...conditions) : undefined; }
function map(row: typeof auditLogs.$inferSelect): AuditListItem { return { id: row.id, createdAt: row.createdAt, actorId: row.actorId, actorRole: row.actorRole, action: row.action, module: row.module || row.action.split(".")[0] || "system", entityType: row.entityType, entityId: row.entityId, before: row.before, after: row.after, origin: row.origin ?? (typeof row.metadata?.origin === "string" ? row.metadata.origin : typeof row.metadata?.ip === "string" ? row.metadata.ip : null), requestId: row.requestId ?? (typeof row.metadata?.requestId === "string" ? row.metadata.requestId : null), correlationId: row.correlationId ?? (typeof row.metadata?.correlationId === "string" ? row.metadata.correlationId : null), metadata: row.metadata, severity: auditSeverity(row.action, row.severity) }; }
export async function getAuditPage(filters: AuditFilters = {}): Promise<AuditPageResponse> { const page = Math.max(1, Math.floor(filters.page ?? 1)); const pageSize = Math.min(maxPageSize, Math.max(1, Math.floor(filters.pageSize ?? defaultPageSize))); const db = getDb(); const where = whereAudit(filters); const failedCondition = or(ilike(auditLogs.action, "%failed%"), ilike(auditLogs.action, "%denied%"), ilike(auditLogs.action, "%invalid%")); const [rows, totalRows, criticalRows, actorRows, failedRows, moduleFacets, actionFacets, entityFacets, severityFacets] = await Promise.all([db.select().from(auditLogs).where(where).orderBy(desc(auditLogs.createdAt), asc(auditLogs.id)).limit(pageSize).offset((page - 1) * pageSize), db.select({ total: count(auditLogs.id) }).from(auditLogs).where(where), db.select({ total: count(auditLogs.id) }).from(auditLogs).where(and(where, or(eq(auditLogs.severity, "CRITICAL"), failedCondition)!)), db.select({ total: countDistinct(auditLogs.actorId) }).from(auditLogs).where(and(where, isNotNull(auditLogs.actorId))), db.select({ total: count(auditLogs.id) }).from(auditLogs).where(and(where, failedCondition)), db.selectDistinct({ value: auditLogs.module }).from(auditLogs).where(where).orderBy(auditLogs.module), db.selectDistinct({ value: auditLogs.action }).from(auditLogs).where(where).orderBy(auditLogs.action), db.selectDistinct({ value: auditLogs.entityType }).from(auditLogs).where(where).orderBy(auditLogs.entityType), db.selectDistinct({ value: auditLogs.severity }).from(auditLogs).where(where).orderBy(auditLogs.severity)]); const totalItems = n(totalRows[0]?.total); const failedCount = n(failedRows[0]?.total); const items = rows.map(map); return { items, page: Math.min(page, Math.max(1, Math.ceil(totalItems / pageSize))), pageSize, totalItems, totalPages: Math.max(1, Math.ceil(totalItems / pageSize)), metrics: { total: totalItems, critical: n(criticalRows[0]?.total), actors: n(actorRows[0]?.total), failedAttempts: failedCount > 0 ? failedCount : null }, facets: { modules: moduleFacets.flatMap((row) => row.value ? [row.value] : []), actions: actionFacets.map((row) => row.value), entityTypes: entityFacets.map((row) => row.value), severities: severityFacets.map((row) => row.value) } }; }
export async function getAuditDetail(id: string) { const [row] = await getDb().select().from(auditLogs).where(eq(auditLogs.id, id)).limit(1); return row ? map(row) : null; }
