import { mediaStatusEnum } from "@/db/schema";

export class MediaInvalidFilterError extends Error { constructor() { super("MEDIA_INVALID_FILTER"); this.name = "MediaInvalidFilterError"; } }
export type MediaFilters = { query?: string; mimeType?: string; status?: (typeof mediaStatusEnum.enumValues)[number]; usage?: "used" | "unused"; dateFrom?: string; dateTo?: string; page?: number; pageSize?: number };
function text(params: URLSearchParams, key: string) { const value = params.get(key)?.trim(); return value || undefined; }
function positive(params: URLSearchParams, key: string) { const raw = params.get(key); if (!raw) return undefined; const value = Number(raw); if (!Number.isInteger(value) || value < 1) throw new MediaInvalidFilterError(); return value; }
function date(params: URLSearchParams, key: string) { const value = text(params, key); if (value && !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new MediaInvalidFilterError(); return value; }
export function parseMediaFilters(params: URLSearchParams): MediaFilters { const status = text(params, "status"); const usage = text(params, "usage"); if (status && !(mediaStatusEnum.enumValues as readonly string[]).includes(status)) throw new MediaInvalidFilterError(); if (usage && usage !== "used" && usage !== "unused") throw new MediaInvalidFilterError(); const dateFrom = date(params, "dateFrom"); const dateTo = date(params, "dateTo"); if (dateFrom && dateTo && dateFrom > dateTo) throw new MediaInvalidFilterError(); return { query: text(params, "query") ?? text(params, "q"), mimeType: text(params, "mimeType"), status: status as MediaFilters["status"], usage: usage as MediaFilters["usage"], dateFrom, dateTo, page: positive(params, "page"), pageSize: positive(params, "pageSize") }; }
export type MediaListItem = { id: string; url: string; originalFilename: string; mimeType: string; byteSize: number; width: number | null; height: number | null; altText: string | null; status: string; uploadedBy: string | null; usageCount: number; createdAt: Date; updatedAt: Date };
export type MediaAssetView = Omit<MediaListItem, "usageCount" | "updatedAt">;
export type MediaPageResponse = { items: MediaListItem[]; page: number; pageSize: number; totalItems: number; totalPages: number; metrics: { total: number; active: number; archived: number; used: number; unused: number; totalBytes: number }; facets: { mimeTypes: string[]; statuses: string[] } };
