import { and, asc, count, desc, eq, gte, ilike, lt, sum, type SQL } from "drizzle-orm";
import { getDb } from "@/db";
import { locations } from "@/db/schema";
import { purchaseItems, purchaseReceiptItems, purchaseReceipts, purchases, suppliers } from "@/db/purchases-schema";
import type { PurchasesFilters, PurchaseListItem, PurchasesPageResponse } from "@/lib/purchases-contract";
const defaultPageSize=25,maxPageSize=100;function pageValues(page?:number,pageSize?:number){return{page:Math.max(1,Math.floor(page??1)),pageSize:Math.min(maxPageSize,Math.max(1,Math.floor(pageSize??defaultPageSize)))}}function dayStart(v:string){return new Date(`${v}T00:00:00-05:00`)}function dayAfter(v:string){return new Date(dayStart(v).getTime()+86_400_000)}function num(v:unknown){return Number(v??0)}
function wherePurchases(f:PurchasesFilters){const c:SQL[]=[];if(f.query){const p=`%${f.query.trim()}%`;c.push(ilike(purchases.code,p))}if(f.status)c.push(eq(purchases.status,f.status));if(f.supplierId)c.push(eq(purchases.supplierId,f.supplierId));if(f.locationId)c.push(eq(purchases.locationId,f.locationId));if(f.currency)c.push(eq(purchases.currency,f.currency));if(f.createdFrom)c.push(gte(purchases.createdAt,dayStart(f.createdFrom)));if(f.createdTo)c.push(lt(purchases.createdAt,dayAfter(f.createdTo)));return c.length?and(...c):undefined}
export async function getPurchasesPage(filters:PurchasesFilters={}):Promise<PurchasesPageResponse>{const{page,pageSize}=pageValues(filters.page,filters.pageSize);const where=wherePurchases(filters);const db=getDb();const[rows,totalRows,statusRows,amountRow,statusFacets,currencyFacets,supplierFacets]=await Promise.all([db.select({purchase:purchases,supplierName:suppliers.name}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(where).orderBy(desc(purchases.updatedAt),asc(purchases.code)).limit(pageSize).offset((page-1)*pageSize),db.select({total:count(purchases.id)}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(where),db.select({status:purchases.status,total:count(purchases.id)}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(where).groupBy(purchases.status),db.select({total:sum(purchases.subtotal)}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(where),db.selectDistinct({value:purchases.status}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(where).orderBy(purchases.status),db.selectDistinct({value:purchases.currency}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(where).orderBy(purchases.currency),db.selectDistinct({id:suppliers.id,name:suppliers.name}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).where(where).orderBy(suppliers.name)]);const totalItems=num(totalRows[0]?.total),map=new Map(statusRows.map(r=>[r.status,num(r.total)]));const items:PurchaseListItem[]=rows.map(r=>({...r.purchase,supplierName:r.supplierName}));return{items,page:Math.min(page,Math.max(1,Math.ceil(totalItems/pageSize))),pageSize,totalItems,totalPages:Math.max(1,Math.ceil(totalItems/pageSize)),metrics:{total:totalItems,pending:map.get("PENDING")??0,partialReceived:map.get("PARTIAL_RECEIVED")??0,received:map.get("RECEIVED")??0,cancelled:map.get("CANCELLED")??0,totalAmount:num(amountRow[0]?.total)},facets:{statuses:statusFacets.map(r=>r.value),currencies:currencyFacets.map(r=>r.value),suppliers:supplierFacets}}}
export async function getPurchaseDetail(purchaseId:string){const db=getDb();const[row]=await db.select({purchase:purchases,supplier:suppliers,location:locations}).from(purchases).innerJoin(suppliers,eq(purchases.supplierId,suppliers.id)).innerJoin(locations,eq(purchases.locationId,locations.id)).where(eq(purchases.id,purchaseId)).limit(1);if(!row)return null;const items=await db.select().from(purchaseItems).where(eq(purchaseItems.purchaseId,purchaseId)).orderBy(asc(purchaseItems.createdAt));const receipts=await db.select({receipt:purchaseReceipts,item:purchaseReceiptItems}).from(purchaseReceipts).leftJoin(purchaseReceiptItems,eq(purchaseReceiptItems.receiptId,purchaseReceipts.id)).where(eq(purchaseReceipts.purchaseId,purchaseId)).orderBy(desc(purchaseReceipts.createdAt));return{purchase:row.purchase,supplier:row.supplier,location:row.location,items,receipts}}
