import { purchaseStatusEnum } from "@/db/purchases-schema";
export class PurchasesInvalidFilterError extends Error{constructor(){super("PURCHASES_INVALID_FILTER");this.name="PurchasesInvalidFilterError"}}
export type PurchasesFilters={query?:string;status?:(typeof purchaseStatusEnum.enumValues)[number];supplierId?:string;locationId?:string;currency?:string;createdFrom?:string;createdTo?:string;expectedFrom?:string;expectedTo?:string;attention?:"DELAYED"|"PARTIAL"|"INCIDENT"|"NORMAL";page?:number;pageSize?:number};
function text(p:URLSearchParams,k:string){const v=p.get(k)?.trim();return v||undefined}function positive(p:URLSearchParams,k:string){const r=p.get(k);if(r===null||r==="")return undefined;const v=Number(r);if(!Number.isInteger(v)||v<1)throw new PurchasesInvalidFilterError();return v}function date(p:URLSearchParams,k:string){const v=text(p,k);if(v&&!/^\d{4}-\d{2}-\d{2}$/.test(v))throw new PurchasesInvalidFilterError();return v}
export function parsePurchasesFilters(p:URLSearchParams):PurchasesFilters{const status=text(p,"status");if(status&&!(purchaseStatusEnum.enumValues as readonly string[]).includes(status))throw new PurchasesInvalidFilterError();const attention=text(p,"attention");if(attention&&!(["DELAYED","PARTIAL","INCIDENT","NORMAL"] as readonly string[]).includes(attention))throw new PurchasesInvalidFilterError();const createdFrom=date(p,"createdFrom"),createdTo=date(p,"createdTo"),expectedFrom=date(p,"expectedFrom"),expectedTo=date(p,"expectedTo");if((createdFrom&&createdTo&&createdFrom>createdTo)||(expectedFrom&&expectedTo&&expectedFrom>expectedTo))throw new PurchasesInvalidFilterError();return{query:text(p,"query")??text(p,"q"),status:status as PurchasesFilters["status"],supplierId:text(p,"supplierId"),locationId:text(p,"locationId"),currency:text(p,"currency"),createdFrom,createdTo,expectedFrom,expectedTo,attention:attention as PurchasesFilters["attention"],page:positive(p,"page"),pageSize:positive(p,"pageSize")}}
export type PurchaseListItem={id:string;code:string;supplierId:string;supplierName:string;locationId:string;status:string;currency:string;subtotal:string;createdAt:Date;updatedAt:Date;issuedAt:Date|null;expectedDeliveryAt:Date|null};
export type PurchasesPageResponse={items:PurchaseListItem[];page:number;pageSize:number;totalItems:number;totalPages:number;metrics:{total:number;pending:number;partialReceived:number;received:number;cancelled:number;totalAmount:number;amountsByCurrency:Array<{currency:string;amount:number}>;leadTimeDays:number|null;incidents:number};facets:{statuses:string[];currencies:string[];suppliers:Array<{id:string;name:string}>}};
export type PurchaseRequestListItem={id:string;code:string;locationId:string;source:string;status:string;notes:string|null;createdAt:Date;updatedAt:Date;itemCount:number};
export type PurchaseRequestsPageResponse={items:PurchaseRequestListItem[];page:number;pageSize:number;totalItems:number;totalPages:number;metrics:{pending:number;draft:number;approved:number;rejected:number;converted:number};facets:{statuses:string[];sources:string[]}};
