import { saleStatusEnum } from "@/db/sales-schema";

export class SalesInvalidFilterError extends Error { constructor() { super("SALES_INVALID_FILTER"); this.name = "SalesInvalidFilterError"; } }
export type SalesFilters = { query?: string; status?: (typeof saleStatusEnum.enumValues)[number]; sellerId?: string; customerId?: string; quoteId?: string; orderId?: string; paymentStatus?: string; invoiceStatus?: string; currency?: string; dateFrom?: string; dateTo?: string; createdFrom?: string; createdTo?: string; page?: number; pageSize?: number };
function text(params: URLSearchParams, key: string) { const value = params.get(key)?.trim(); return value || undefined; }
function positive(params: URLSearchParams, key: string) { const raw=params.get(key); if(raw===null||raw==="") return undefined; const value=Number(raw); if(!Number.isInteger(value)||value<1) throw new SalesInvalidFilterError(); return value; }
function date(params: URLSearchParams, key: string) { const value=text(params,key); if(value&&!/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new SalesInvalidFilterError(); return value; }
export function parseSalesFilters(params: URLSearchParams): SalesFilters { const status=text(params,"status"); if(status&&!(saleStatusEnum.enumValues as readonly string[]).includes(status)) throw new SalesInvalidFilterError(); const dateFrom=date(params,"dateFrom") ?? date(params,"createdFrom"); const dateTo=date(params,"dateTo") ?? date(params,"createdTo"); if(dateFrom&&dateTo&&dateFrom>dateTo) throw new SalesInvalidFilterError(); return { query:text(params,"query")??text(params,"q"), status:status as SalesFilters["status"], sellerId:text(params,"sellerId"), customerId:text(params,"customerId"), quoteId:text(params,"quoteId"), orderId:text(params,"orderId"), paymentStatus:text(params,"paymentStatus"), invoiceStatus:text(params,"invoiceStatus"), currency:text(params,"currency"), dateFrom, dateTo, createdFrom: dateFrom, createdTo: dateTo, page:positive(params,"page"), pageSize:positive(params,"pageSize") }; }
export type SalesListItem = { id: string; code: string; customerId: string; customerName: string; customerEmail: string | null; sellerId: string | null; sellerName: string | null; sellerEmail: string | null; quoteId: string | null; quoteTrackingCode: string | null; opportunityId: string | null; opportunityCode: string | null; opportunityTitle: string | null; orderId: string | null; orderCode: string | null; orderStatus: string | null; lineCount: number; paymentStatus: string | null; status: string; subtotal: string; discountAmount: string; total: string; currency: string; invoiceStatus: string | null; externalInvoiceReference: string | null; createdAt: Date; updatedAt: Date };
export type SalesPageResponse = { items: SalesListItem[]; page: number; pageSize: number; totalItems: number; totalPages: number; metrics: { total: number; confirmed: number; cancelled: number; pending: number; totalAmount: number; averageTicket: number | null; conversionRate: number | null }; facets: { statuses: string[]; currencies: string[] } };
