import { and, count, eq, sql } from "drizzle-orm";
import { ApiAuthorizationError, requireApiPermission } from "@/lib/auth";
import { apiError, apiSuccess } from "@/lib/api-errors";
import { getDb } from "@/db";
import { auditLogs, brands, categories, families, products } from "@/db/schema";
import { getTaxonomyPage, isTaxonomyEntity, parseTaxonomyFilters, slugifyTaxonomy, taxonomyEntities, taxonomyPermission, TaxonomyInvalidFilterError, type TaxonomyEntity } from "@/lib/taxonomy-admin";

async function requireTaxonomyAccess(entity: TaxonomyEntity) { try { return await requireApiPermission(taxonomyPermission(entity)); } catch (error) { if (error instanceof ApiAuthorizationError) return requireApiPermission("catalog.product.edit"); throw error; } }
function input(body: unknown) { if (!body || typeof body !== "object" || Array.isArray(body)) throw new Error("El cuerpo debe ser un objeto."); const value = body as Record<string, unknown>; const name = typeof value.name === "string" ? value.name.trim().slice(0, 160) : ""; const slug = typeof value.slug === "string" && value.slug.trim() ? slugifyTaxonomy(value.slug) : slugifyTaxonomy(name); const categoryId = typeof value.categoryId === "string" && value.categoryId.trim() ? value.categoryId.trim() : null; if (name.length < 2 || !slug) throw new Error("Nombre y slug válidos son obligatorios."); return { name, slug, categoryId }; }
async function assertUnique(tx: Parameters<Parameters<ReturnType<typeof getDb>["transaction"]>[0]>[0], entity: TaxonomyEntity, name: string, slug: string, excludeId?: string) { const sameSlug = entity === "categories" ? await tx.select({ id: categories.id }).from(categories).where(sql`lower(${categories.slug}) = lower(${slug})`).limit(1) : entity === "families" ? await tx.select({ id: families.id }).from(families).where(sql`lower(${families.slug}) = lower(${slug})`).limit(1) : await tx.select({ id: brands.id }).from(brands).where(sql`lower(${brands.slug}) = lower(${slug})`).limit(1); const sameName = entity === "categories" ? await tx.select({ id: categories.id }).from(categories).where(sql`lower(${categories.name}) = lower(${name})`).limit(1) : entity === "families" ? await tx.select({ id: families.id }).from(families).where(sql`lower(${families.name}) = lower(${name})`).limit(1) : await tx.select({ id: brands.id }).from(brands).where(sql`lower(${brands.name}) = lower(${name})`).limit(1); if ((sameSlug[0] && sameSlug[0].id !== excludeId) || (sameName[0] && sameName[0].id !== excludeId)) throw new Error("Ya existe una entidad con ese nombre o slug (la comparación no distingue mayúsculas). "); }

export async function GET(request: Request) { const params = new URL(request.url).searchParams; const entity = params.get("entity") ?? "categories"; if (!isTaxonomyEntity(entity)) return apiError("TAXONOMY_INVALID_ENTITY", "Entidad de taxonomía inválida.", 400); try { await requireTaxonomyAccess(entity); return apiSuccess(await getTaxonomyPage(parseTaxonomyFilters(new URLSearchParams(params)))); } catch (error) { if (error instanceof ApiAuthorizationError) return apiError("TAXONOMY_FORBIDDEN", "No tienes permiso para ver esta taxonomía.", 403); if (error instanceof TaxonomyInvalidFilterError) return apiError("TAXONOMY_INVALID_FILTER", "Los filtros de taxonomía no son válidos.", 400); return apiError("TAXONOMY_UNAVAILABLE", "No se pudo cargar la taxonomía.", 503); } }

export async function POST(request: Request) { const entityValue = new URL(request.url).searchParams.get("entity"); if (!isTaxonomyEntity(entityValue)) return apiError("TAXONOMY_INVALID_ENTITY", "Entidad de taxonomía inválida.", 400); try { const actor = await requireTaxonomyAccess(entityValue); const value = input(await request.json()); if (entityValue === "families" && !value.categoryId) throw new Error("Una familia debe pertenecer a una categoría."); const result = await getDb().transaction(async (tx) => { const id = `taxonomy-${entityValue.slice(0, -1)}-${crypto.randomUUID()}`; await assertUnique(tx, entityValue, value.name, value.slug); if (entityValue === "families") { const [parent] = await tx.select({ id: categories.id, active: categories.active }).from(categories).where(eq(categories.id, value.categoryId!)).limit(1); if (!parent || !parent.active) throw new Error("La categoría padre no existe o está inactiva."); } const created = entityValue === "categories" ? (await tx.insert(categories).values({ id, name: value.name, slug: value.slug }).returning())[0] : entityValue === "families" ? (await tx.insert(families).values({ id, name: value.name, slug: value.slug, categoryId: value.categoryId! }).returning())[0] : (await tx.insert(brands).values({ id, name: value.name, slug: value.slug }).returning())[0]; await tx.insert(auditLogs).values({ id: `audit-${crypto.randomUUID()}`, actorId: actor.userId, actorRole: actor.role, action: `catalog.${entityValue}.created`, entityType: entityValue.slice(0, -1), entityId: id, before: null, after: created, metadata: null }); return created; }); return apiSuccess({ result }, 201); } catch (error) { if (error instanceof ApiAuthorizationError) return apiError("TAXONOMY_FORBIDDEN", "No tienes permiso para modificar esta taxonomía.", 403); return apiError("TAXONOMY_CREATE_FAILED", error instanceof Error ? error.message : "No se pudo crear la entidad.", 409); } }

export function OPTIONS() { return apiSuccess({ entities: taxonomyEntities }); }
