import { and, eq } from "drizzle-orm";
import { ApiAuthorizationError, requireApiPermission } from "@/lib/auth";
import { apiError, apiSuccess } from "@/lib/api-errors";
import { getDb } from "@/db";
import { auditLogs, mediaAssetUsages, mediaAssets } from "@/db/schema";

const entityTypes = ["product", "category", "brand", "cms_page", "cms_block", "company_settings"] as const;
function validUsage(body: unknown) { const value = body && typeof body === "object" ? body as Record<string, unknown> : {}; const entityType = typeof value.entityType === "string" && (entityTypes as readonly string[]).includes(value.entityType) ? value.entityType : null; const entityId = typeof value.entityId === "string" && /^[A-Za-z0-9:_-]{1,160}$/.test(value.entityId) ? value.entityId : null; const slot = typeof value.slot === "string" && /^[a-z0-9][a-z0-9_-]{0,80}$/.test(value.slot) ? value.slot : null; const sortOrder = Number.isInteger(value.sortOrder) && Number(value.sortOrder) >= 0 ? Number(value.sortOrder) : 0; return entityType && entityId && slot ? { entityType, entityId, slot, sortOrder } : null; }

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { try { await requireApiPermission("media.view"); const { id } = await params; return apiSuccess({ usages: await getDb().select().from(mediaAssetUsages).where(eq(mediaAssetUsages.assetId, id)).orderBy(mediaAssetUsages.createdAt) }); } catch (error) { if (error instanceof ApiAuthorizationError) return apiError("MEDIA_FORBIDDEN", "No tienes permiso para ver usos de media.", 403); return apiError("MEDIA_USAGE_UNAVAILABLE", "No se pudieron cargar los usos de media.", 503); } }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const actor = await requireApiPermission("catalog.media.upload"); const { id } = await params; let body: unknown; try { body = await request.json(); } catch { return apiError("INVALID_JSON", "JSON inválido.", 400); } const usage = validUsage(body); if (!usage) return apiError("MEDIA_USAGE_INVALID", "Uso multimedia inválido.", 400); const result = await getDb().transaction(async (tx) => { const [asset] = await tx.select({ id: mediaAssets.id }).from(mediaAssets).where(and(eq(mediaAssets.id, id), eq(mediaAssets.status, "ACTIVE"))).limit(1); if (!asset) throw new Error("MEDIA_NOT_FOUND"); const [created] = await tx.insert(mediaAssetUsages).values({ id: `media-use-${crypto.randomUUID()}`, assetId: id, ...usage }).onConflictDoUpdate({ target: [mediaAssetUsages.assetId, mediaAssetUsages.entityType, mediaAssetUsages.entityId, mediaAssetUsages.slot], set: { sortOrder: usage.sortOrder } }).returning(); await tx.insert(auditLogs).values({ id: `audit-${crypto.randomUUID()}`, actorId: actor.userId, actorRole: actor.role, action: "media.asset_associated", entityType: usage.entityType, entityId: usage.entityId, before: null, after: { assetId: id, slot: usage.slot, sortOrder: usage.sortOrder }, metadata: null }); return created; }); return apiSuccess({ usage: result }, 201); } catch (error) { if (error instanceof ApiAuthorizationError) return apiError("MEDIA_ASSOCIATE_FORBIDDEN", "No tienes permiso para asociar media.", 403); return apiError("MEDIA_ASSOCIATE_FAILED", error instanceof Error && error.message === "MEDIA_NOT_FOUND" ? "La media no existe o está archivada." : error instanceof Error ? error.message : "No se pudo asociar la media.", 409); } }
export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const actor = await requireApiPermission("catalog.media.upload"); const { id } = await params; let body: unknown; try { body = await request.json(); } catch { return apiError("INVALID_JSON", "JSON inválido.", 400); } const usage = validUsage(body); if (!usage) return apiError("MEDIA_USAGE_INVALID", "Uso multimedia inválido.", 400); await getDb().transaction(async (tx) => { await tx.delete(mediaAssetUsages).where(and(eq(mediaAssetUsages.assetId, id), eq(mediaAssetUsages.entityType, usage.entityType), eq(mediaAssetUsages.entityId, usage.entityId), eq(mediaAssetUsages.slot, usage.slot))); await tx.insert(auditLogs).values({ id: `audit-${crypto.randomUUID()}`, actorId: actor.userId, actorRole: actor.role, action: "media.asset_disassociated", entityType: usage.entityType, entityId: usage.entityId, before: { assetId: id, slot: usage.slot }, after: null, metadata: null }); }); return apiSuccess({ success: true }); } catch (error) { if (error instanceof ApiAuthorizationError) return apiError("MEDIA_DISASSOCIATE_FORBIDDEN", "No tienes permiso para desasociar media.", 403); return apiError("MEDIA_DISASSOCIATE_FAILED", error instanceof Error ? error.message : "No se pudo desasociar la media.", 409); } }
