import type { Category } from "@/types/category";

// Categorías generadas a partir del reporte de productos real de ColdPower (inventario),
// clasificadas por sector. Los conteos reflejan el catálogo cargado en src/data/products.ts.
export const categories: Category[] = [
  {
    id: "cat-refrigeracion",
    slug: "refrigeracion",
    name: "Refrigeración",
    description: "Compresores, capacitores, termostatos, válvulas, gases refrigerantes y repuestos para equipos de refrigeración comercial e industrial.",
    image: "/images/cat-refrigeracion.svg",
    featured: true,
  },
  {
    id: "cat-repuestos-y-accesorios-generales",
    slug: "repuestos-y-accesorios-generales",
    name: "Repuestos y accesorios generales",
    description: "Piezas, herramientas y accesorios de uso general y multimarca para distintos equipos y electrodomésticos.",
    image: "/images/cat-repuestos-y-accesorios-generales.svg",
    featured: false,
  },
  {
    id: "cat-lavadora",
    slug: "lavadora",
    name: "Lavadoras",
    description: "Repuestos para lavadoras: rodajes, retenes, mangueras, tarjetas, bombas, fajas y componentes de transmisión.",
    image: "/images/cat-lavadora.svg",
    featured: true,
  },
  {
    id: "cat-licuadora",
    slug: "licuadora",
    name: "Licuadoras",
    description: "Cuchillas, vasos, acoples, bases y repuestos para licuadoras y extractores.",
    image: "/images/cat-licuadora.svg",
    featured: true,
  },
  {
    id: "cat-bomba-de-agua",
    slug: "bomba-de-agua",
    name: "Bombas de agua",
    description: "Sellos, platinos y repuestos para bombas de agua domésticas e industriales.",
    image: "/images/cat-bomba-de-agua.svg",
    featured: true,
  },
  {
    id: "cat-cocina",
    slug: "cocina",
    name: "Cocinas",
    description: "Hornillas, chisperos, válvulas y termostatos para cocinas a gas.",
    image: "/images/cat-cocina.svg",
    featured: true,
  },
  {
    id: "cat-motores-automotrices",
    slug: "motores-automotrices",
    name: "Motores automotrices",
    description: "Motores nuevos semiarmados y monoblock con culata para uso automotriz.",
    image: "/images/cat-motores-automotrices.svg",
    featured: true,
  },
  {
    id: "cat-campana-extractora",
    slug: "campana-extractora",
    name: "Campanas extractoras",
    description: "Filtros de aluminio y repuestos para campanas extractoras de cocina.",
    image: "/images/cat-campana-extractora.svg",
    featured: true,
  },
  {
    id: "cat-secadora",
    slug: "secadora",
    name: "Secadoras",
    description: "Termostatos, fajas y resistencias para secadoras de ropa.",
    image: "/images/cat-secadora.svg",
    featured: false,
  },
  {
    id: "cat-lustradoras",
    slug: "lustradoras",
    name: "Lustradoras",
    description: "Escobillas y repuestos para lustradoras de piso.",
    image: "/images/cat-lustradoras.svg",
    featured: false,
  },
  {
    id: "cat-otros-electrodomesticos",
    slug: "otros-electrodomesticos",
    name: "Otros electrodomésticos",
    description: "Repuestos varios para duchas eléctricas, microondas, congeladoras y otros electrodomésticos.",
    image: "/images/cat-otros-electrodomesticos.svg",
    featured: false,
  },
  {
    id: "cat-terma",
    slug: "terma",
    name: "Termas",
    description: "Resistencias, válvulas y termostatos para termas eléctricas.",
    image: "/images/cat-terma.svg",
    featured: false,
  },
  {
    id: "cat-hervidor",
    slug: "hervidor",
    name: "Hervidores",
    description: "Resistencias y termostatos para hervidores eléctricos.",
    image: "/images/cat-hervidor.svg",
    featured: false,
  },
  {
    id: "cat-extractor",
    slug: "extractor",
    name: "Extractores",
    description: "Filtros y focos para campanas y extractores de cocina.",
    image: "/images/cat-extractor.svg",
    featured: false,
  },
  {
    id: "cat-plancha",
    slug: "plancha",
    name: "Planchas",
    description: "Termostatos y repuestos para planchas eléctricas.",
    image: "/images/cat-plancha.svg",
    featured: false,
  },
  {
    id: "cat-arrocera",
    slug: "arrocera",
    name: "Arroceras",
    description: "Sensores y resistencias para ollas arroceras.",
    image: "/images/cat-arrocera.svg",
    featured: false,
  },
];
