import { desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { ApiAuthorizationError, requireApiPermission } from "@/lib/auth";
import { getDb } from "@/db";
import { locations, quoteItems, quotes } from "@/db/schema";
import { sales } from "@/db/sales-schema";
import { convertQuoteToSale } from "@/lib/sales-service";
import { getSalesPage } from "@/lib/sales-repository";
import { parseSalesFilters, SalesInvalidFilterError } from "@/lib/sales-contract";
import { apiError, apiSuccess } from "@/lib/api-errors";

export async function GET(request: Request) { try { await requireApiPermission("sales.view"); const quoteId = new URL(request.url).searchParams.get("quoteId")?.trim(); if (quoteId) { const [quote] = await getDb().select({ id: quotes.id }).from(quotes).where(eq(quotes.id, quoteId)).limit(1); if (!quote) return apiError("QUOTE_NOT_FOUND", "Cotización no encontrada.", 404); const [items, activeLocations] = await Promise.all([getDb().select({ productId: quoteItems.productId, sku: quoteItems.skuSnapshot, name: quoteItems.productNameSnapshot, quantity: quoteItems.quantity }).from(quoteItems).where(eq(quoteItems.quoteId, quoteId)).orderBy(desc(quoteItems.createdAt)), getDb().select({ id: locations.id, name: locations.name, address: locations.address }).from(locations).where(eq(locations.active, true)).orderBy(locations.name)]); return apiSuccess({ items: items.map((item) => ({ ...item, unitPrice: "", currency: "PEN" })), locations: activeLocations }); } return apiSuccess(await getSalesPage(parseSalesFilters(new URL(request.url).searchParams))); } catch(error) { if(error instanceof ApiAuthorizationError)return apiError("SALES_FORBIDDEN","No tienes permiso para ver ventas.",403); if(error instanceof SalesInvalidFilterError)return apiError("SALES_INVALID_FILTER","Los filtros de ventas no son válidos.",400); return apiError("SALES_UNAVAILABLE","No se pudieron cargar las ventas.",503); } }
export async function POST(request: Request) { try { const actor = await requireApiPermission("sales.manage"); let body: unknown; try { body = await request.json(); } catch { return apiError("INVALID_JSON", "JSON inválido.", 400); } const value = body && typeof body === "object" ? body as Record<string, unknown> : {}; const items = Array.isArray(value.items) ? value.items.flatMap((item) => { if (!item || typeof item !== "object") return []; const row = item as Record<string, unknown>; return typeof row.productId === "string" && typeof row.unitPrice === "string" && typeof row.currency === "string" ? [{ productId: row.productId, unitPrice: row.unitPrice, currency: row.currency }] : []; }) : []; const result = await convertQuoteToSale({ quoteId: typeof value.quoteId === "string" ? value.quoteId : "", locationId: typeof value.locationId === "string" ? value.locationId : "", deliveryMethod: value.deliveryMethod === "DELIVERY" || value.deliveryMethod === "SHIPPING" ? value.deliveryMethod : "PICKUP", address: typeof value.address === "string" ? value.address.trim().slice(0, 300) || null : null, items }, actor); return apiSuccess({ success: true, ...result }, result.idempotent ? 200 : 201); } catch(error) { if(error instanceof ApiAuthorizationError)return apiError("SALES_FORBIDDEN","No tienes permiso para convertir ventas.",403); return apiError("SALE_NOT_CREATED",error instanceof Error?error.message:"No se pudo convertir la cotización.",400); } }
