import {
  boolean,
  check,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { products, quotes, users } from "@/db/schema";

export const customerTypeEnum = pgEnum("customer_type", ["PERSON", "COMPANY", "CONSUMIDOR", "TECNICO", "EMPRESA", "DISTRIBUIDOR", "MAYORISTA"]);
export const customerStatusEnum = pgEnum("customer_status", ["ACTIVE", "INACTIVE", "PROSPECT"]);
export const opportunityStageEnum = pgEnum("opportunity_stage", ["NEW", "CONTACTED", "QUOTING", "QUOTE_SENT", "FOLLOW_UP", "NEGOTIATION", "ACCEPTED", "SALE", "PAYMENT_PENDING", "PAID", "PREPARING", "DELIVERED", "CLOSED", "LOST", "CANCELLED", "NO_RESPONSE"]);
export const opportunityOriginEnum = pgEnum("opportunity_origin", ["WEB", "WHATSAPP", "TELEFONO", "LOCAL", "REFERIDO", "CLIENTE_RECURRENTE", "OTRO"]);
export const crmActivityTypeEnum = pgEnum("crm_activity_type", ["CALL", "WHATSAPP", "EMAIL", "MEETING", "TASK", "NOTE"]);
export const crmTaskStatusEnum = pgEnum("crm_task_status", ["PENDING", "COMPLETED", "OVERDUE", "CANCELLED"]);

export const customers = pgTable("customers", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "set null" }), name: text("name").notNull(), legalName: text("legal_name"), documentNumber: text("document_number"), ruc: text("ruc"), phone: text("phone"), whatsapp: text("whatsapp"), email: text("email"), address: text("address"), location: text("location"), contactPreference: text("contact_preference"), customerType: customerTypeEnum("customer_type").notNull().default("CONSUMIDOR"), assignedSellerId: text("assigned_seller_id"), notes: text("notes"), status: customerStatusEnum("status").notNull().default("PROSPECT"), canonicalCustomerId: text("canonical_customer_id"), mergeReason: text("merge_reason"), mergedBy: text("merged_by"), mergedAt: timestamp("merged_at", { withTimezone: true }), lastActivityAt: timestamp("last_activity_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ emailIndex: index("customers_email_idx").on(table.email), phoneIndex: index("customers_phone_idx").on(table.phone), statusIndex: index("customers_status_idx").on(table.status), sellerIndex: index("customers_assigned_seller_idx").on(table.assignedSellerId), activityIndex: index("customers_last_activity_idx").on(table.lastActivityAt), canonicalIndex: index("customers_canonical_idx").on(table.canonicalCustomerId), userUnique: uniqueIndex("customers_user_id_unique").on(table.userId) }));
export const customerContacts = pgTable("customer_contacts", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id, { onDelete: "cascade" }), name: text("name").notNull(), role: text("role"), email: text("email"), phone: text("phone"), whatsapp: text("whatsapp"), status: text("status").notNull().default("ACTIVE"), isPrimary: boolean("is_primary").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ customerIndex: index("customer_contacts_customer_idx").on(table.customerId), primaryIndex: index("customer_contacts_primary_idx").on(table.customerId, table.isPrimary) }));
export const customerNotes = pgTable("customer_notes", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id, { onDelete: "cascade" }), body: text("body").notNull(), createdBy: text("created_by"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ customerIndex: index("customer_notes_customer_idx").on(table.customerId, table.createdAt) }));
export const customerAddresses = pgTable("customer_addresses", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id, { onDelete: "cascade" }), label: text("label").notNull(), address: text("address").notNull(), country: text("country"), department: text("department"), province: text("province"), district: text("district"), isPrimary: boolean("is_primary").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ customerIndex: index("customer_addresses_customer_idx").on(table.customerId), primaryIndex: index("customer_addresses_primary_idx").on(table.customerId, table.isPrimary) }));
export const opportunities = pgTable("opportunities", { id: text("id").primaryKey(), code: text("code").notNull(), customerId: text("customer_id").notNull().references(() => customers.id, { onDelete: "restrict" }), quoteId: text("quote_id").references(() => quotes.id, { onDelete: "set null" }), title: text("title").notNull(), origin: opportunityOriginEnum("origin").notNull().default("WEB"), stage: opportunityStageEnum("stage").notNull().default("NEW"), assignedSellerId: text("assigned_seller_id"), totalAmount: numeric("total_amount", { precision: 14, scale: 2 }), currency: varchar("currency", { length: 3 }), discountPercentage: numeric("discount_percentage", { precision: 5, scale: 2 }), marginAmount: numeric("margin_amount", { precision: 14, scale: 2 }), lastContactAt: timestamp("last_contact_at", { withTimezone: true }), nextAction: text("next_action"), followUpAt: timestamp("follow_up_at", { withTimezone: true }), notes: text("notes"), lostReason: text("lost_reason"), createdBy: text("created_by"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ codeUnique: uniqueIndex("opportunities_code_unique_idx").on(table.code), customerIndex: index("opportunities_customer_idx").on(table.customerId), stageIndex: index("opportunities_stage_idx").on(table.stage), sellerIndex: index("opportunities_seller_idx").on(table.assignedSellerId), followUpIndex: index("opportunities_follow_up_idx").on(table.followUpAt), quoteUnique: uniqueIndex("opportunities_quote_unique").on(table.quoteId), createdAtIndex: index("opportunities_created_at_idx").on(table.createdAt) }));
export const opportunityItems = pgTable("opportunity_items", { id: text("id").primaryKey(), opportunityId: text("opportunity_id").notNull().references(() => opportunities.id, { onDelete: "cascade" }), productId: text("product_id").notNull().references(() => products.id, { onDelete: "restrict" }), skuSnapshot: text("sku_snapshot").notNull(), productNameSnapshot: text("product_name_snapshot").notNull(), quantity: integer("quantity").notNull(), unitPrice: numeric("unit_price", { precision: 14, scale: 2 }), currency: varchar("currency", { length: 3 }), discountPercentage: numeric("discount_percentage", { precision: 5, scale: 2 }), lineTotal: numeric("line_total", { precision: 14, scale: 2 }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ opportunityProductUnique: uniqueIndex("opportunity_items_product_unique").on(table.opportunityId, table.productId), opportunityIndex: index("opportunity_items_opportunity_idx").on(table.opportunityId), quantityPositive: check("opportunity_items_quantity_positive", sql.raw("quantity > 0")) }));
export const opportunityStageHistory = pgTable("opportunity_stage_history", { id: text("id").primaryKey(), opportunityId: text("opportunity_id").notNull().references(() => opportunities.id, { onDelete: "cascade" }), fromStage: opportunityStageEnum("from_stage"), toStage: opportunityStageEnum("to_stage").notNull(), changedBy: text("changed_by").notNull(), note: text("note"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ opportunityIndex: index("opportunity_stage_history_opportunity_idx").on(table.opportunityId), createdIndex: index("opportunity_stage_history_created_idx").on(table.createdAt) }));
export const crmActivities = pgTable("crm_activities", { id: text("id").primaryKey(), customerId: text("customer_id").references(() => customers.id, { onDelete: "cascade" }), opportunityId: text("opportunity_id").references(() => opportunities.id, { onDelete: "cascade" }), quoteId: text("quote_id").references(() => quotes.id, { onDelete: "set null" }), type: crmActivityTypeEnum("type").notNull(), subject: text("subject").notNull(), body: text("body"), result: text("result"), occurredAt: timestamp("occurred_at", { withTimezone: true }), nextAction: text("next_action"), nextActionAt: timestamp("next_action_at", { withTimezone: true }), performedBy: text("performed_by"), dueAt: timestamp("due_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), idempotencyKey: text("idempotency_key"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ customerIndex: index("crm_activities_customer_idx").on(table.customerId), opportunityIndex: index("crm_activities_opportunity_idx").on(table.opportunityId), dueIndex: index("crm_activities_due_idx").on(table.dueAt), occurredIndex: index("crm_activities_occurred_idx").on(table.occurredAt), idempotencyUnique: uniqueIndex("crm_activities_idempotency_unique").on(table.idempotencyKey) }));
export const crmTasks = pgTable("crm_tasks", { id: text("id").primaryKey(), customerId: text("customer_id").references(() => customers.id, { onDelete: "cascade" }), opportunityId: text("opportunity_id").references(() => opportunities.id, { onDelete: "cascade" }), quoteId: text("quote_id").references(() => quotes.id, { onDelete: "set null" }), title: text("title").notNull(), description: text("description"), status: crmTaskStatusEnum("status").notNull().default("PENDING"), assignedTo: text("assigned_to"), dueAt: timestamp("due_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), createdBy: text("created_by"), idempotencyKey: text("idempotency_key"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ statusIndex: index("crm_tasks_status_idx").on(table.status), assignedIndex: index("crm_tasks_assigned_idx").on(table.assignedTo), dueIndex: index("crm_tasks_due_idx").on(table.dueAt), idempotencyUnique: uniqueIndex("crm_tasks_idempotency_unique").on(table.idempotencyKey) }));
export const opportunityActivities = pgTable("opportunity_activities", { id: text("id").primaryKey(), opportunityId: text("opportunity_id").notNull().references(() => opportunities.id, { onDelete: "cascade" }), type: crmActivityTypeEnum("type").notNull(), subject: text("subject").notNull(), body: text("body"), performedBy: text("performed_by"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ opportunityIndex: index("opportunity_activities_opportunity_idx").on(table.opportunityId, table.createdAt) }));
export const opportunityFollowups = pgTable("opportunity_followups", { id: text("id").primaryKey(), opportunityId: text("opportunity_id").notNull().references(() => opportunities.id, { onDelete: "cascade" }), title: text("title").notNull(), dueAt: timestamp("due_at", { withTimezone: true }).notNull(), status: crmTaskStatusEnum("status").notNull().default("PENDING"), assignedTo: text("assigned_to"), completedAt: timestamp("completed_at", { withTimezone: true }), createdBy: text("created_by"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ opportunityIndex: index("opportunity_followups_opportunity_idx").on(table.opportunityId), dueIndex: index("opportunity_followups_due_idx").on(table.dueAt, table.status) }));
export const customerQuoteLinks = pgTable("customer_quote_links", { id: text("id").primaryKey(), customerId: text("customer_id").notNull().references(() => customers.id, { onDelete: "cascade" }), quoteId: text("quote_id").notNull().references(() => quotes.id, { onDelete: "cascade" }), opportunityId: text("opportunity_id").references(() => opportunities.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ quoteUnique: uniqueIndex("customer_quote_links_quote_unique").on(table.quoteId), customerIndex: index("customer_quote_links_customer_idx").on(table.customerId) }));
