import { check, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { locations, products, users } from "@/db/schema";

export const supplierStatusEnum = pgEnum("supplier_status", ["ACTIVE", "INACTIVE"]);
export const purchaseStatusEnum = pgEnum("purchase_status", ["DRAFT", "PENDING", "PARTIAL_RECEIVED", "RECEIVED", "CANCELLED"]);
export const purchaseRequestStatusEnum = pgEnum("purchase_request_status", ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED", "CONVERTED", "CANCELLED"]);
export const purchaseRequestSourceEnum = pgEnum("purchase_request_source", ["MANUAL", "STOCK_ALERT", "REPLENISHMENT", "OTHER"]);
export const receiptStatusEnum = pgEnum("purchase_receipt_status", ["POSTED", "CANCELLED"]);

export const suppliers = pgTable("suppliers", { id: text("id").primaryKey(), name: text("name").notNull(), identification: text("identification"), country: varchar("country", { length: 2 }).notNull(), contactName: text("contact_name"), whatsapp: text("whatsapp"), email: text("email"), address: text("address"), currency: varchar("currency", { length: 3 }).notNull(), notes: text("notes"), status: supplierStatusEnum("status").notNull().default("ACTIVE"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ nameIndex: index("suppliers_name_idx").on(table.name), identificationIndex: index("suppliers_identification_idx").on(table.identification), statusIndex: index("suppliers_status_idx").on(table.status) }));
export const purchaseRequests = pgTable("purchase_requests", { id: text("id").primaryKey(), code: text("code").notNull(), requesterId: text("requester_id").references(() => users.id, { onDelete: "set null" }), locationId: text("location_id").references(() => locations.id, { onDelete: "restrict" }), source: purchaseRequestSourceEnum("source").notNull().default("MANUAL"), status: purchaseRequestStatusEnum("status").notNull().default("DRAFT"), notes: text("notes"), rejectionReason: text("rejection_reason"), approvedBy: text("approved_by").references(() => users.id, { onDelete: "set null" }), approvedAt: timestamp("approved_at", { withTimezone: true }), convertedPurchaseId: text("converted_purchase_id"), idempotencyKey: text("idempotency_key"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ codeUnique: uniqueIndex("purchase_requests_code_unique").on(table.code), idempotencyUnique: uniqueIndex("purchase_requests_idempotency_unique").on(table.idempotencyKey), statusIndex: index("purchase_requests_status_idx").on(table.status), sourceIndex: index("purchase_requests_source_idx").on(table.source), requesterIndex: index("purchase_requests_requester_idx").on(table.requesterId) }));
export const purchaseRequestItems = pgTable("purchase_request_items", { id: text("id").primaryKey(), requestId: text("request_id").notNull().references(() => purchaseRequests.id, { onDelete: "cascade" }), productId: text("product_id").notNull().references(() => products.id, { onDelete: "restrict" }), skuSnapshot: text("sku_snapshot").notNull(), productNameSnapshot: text("product_name_snapshot").notNull(), quantityRequested: integer("quantity_requested").notNull(), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ requestProductUnique: uniqueIndex("purchase_request_items_request_product_unique").on(table.requestId, table.productId), quantityPositive: check("purchase_request_items_quantity_positive", sql.raw("quantity_requested > 0")) }));
export const purchases = pgTable("purchases", { id: text("id").primaryKey(), code: text("code").notNull(), supplierId: text("supplier_id").notNull().references(() => suppliers.id, { onDelete: "restrict" }), locationId: text("location_id").notNull().references(() => locations.id, { onDelete: "restrict" }), requestId: text("request_id"), status: purchaseStatusEnum("status").notNull().default("DRAFT"), currency: varchar("currency", { length: 3 }).notNull(), subtotal: numeric("subtotal", { precision: 14, scale: 2 }).notNull().default("0"), notes: text("notes"), issuedAt: timestamp("issued_at", { withTimezone: true }), expectedDeliveryAt: timestamp("expected_delivery_at", { withTimezone: true }), cancelledAt: timestamp("cancelled_at", { withTimezone: true }), cancelledBy: text("cancelled_by").references(() => users.id, { onDelete: "set null" }), cancellationReason: text("cancellation_reason"), createdBy: text("created_by").references(() => users.id, { onDelete: "set null" }), idempotencyKey: text("idempotency_key"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ codeUnique: uniqueIndex("purchases_code_unique").on(table.code), idempotencyUnique: uniqueIndex("purchases_idempotency_unique").on(table.idempotencyKey), supplierIndex: index("purchases_supplier_idx").on(table.supplierId), statusIndex: index("purchases_status_idx").on(table.status), expectedDeliveryIndex: index("purchases_expected_delivery_idx").on(table.expectedDeliveryAt), requestIndex: index("purchases_request_idx").on(table.requestId) }));
export const purchaseItems = pgTable("purchase_items", { id: text("id").primaryKey(), purchaseId: text("purchase_id").notNull().references(() => purchases.id, { onDelete: "cascade" }), productId: text("product_id").notNull().references(() => products.id, { onDelete: "restrict" }), skuSnapshot: text("sku_snapshot").notNull(), productNameSnapshot: text("product_name_snapshot").notNull(), quantityOrdered: integer("quantity_ordered").notNull(), quantityReceived: integer("quantity_received").notNull().default(0), unitCost: numeric("unit_cost", { precision: 14, scale: 2 }).notNull(), currency: varchar("currency", { length: 3 }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ purchaseProductUnique: uniqueIndex("purchase_items_purchase_product_unique").on(table.purchaseId, table.productId), orderedPositive: check("purchase_items_ordered_positive", sql.raw("quantity_ordered > 0")), receivedNonNegative: check("purchase_items_received_nonnegative", sql.raw("quantity_received >= 0 AND quantity_received <= quantity_ordered")) }));
export const purchaseReceipts = pgTable("purchase_receipts", { id: text("id").primaryKey(), code: text("code").notNull(), purchaseId: text("purchase_id").notNull().references(() => purchases.id, { onDelete: "restrict" }), locationId: text("location_id").notNull().references(() => locations.id, { onDelete: "restrict" }), status: receiptStatusEnum("status").notNull().default("POSTED"), receivedBy: text("received_by").references(() => users.id, { onDelete: "set null" }), notes: text("notes"), idempotencyKey: text("idempotency_key"), receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => ({ codeUnique: uniqueIndex("purchase_receipts_code_unique").on(table.code), idempotencyUnique: uniqueIndex("purchase_receipts_idempotency_unique").on(table.idempotencyKey), purchaseIndex: index("purchase_receipts_purchase_idx").on(table.purchaseId), receivedIndex: index("purchase_receipts_received_idx").on(table.receivedAt) }));
export const purchaseReceiptItems = pgTable("purchase_receipt_items", { id: text("id").primaryKey(), receiptId: text("receipt_id").notNull().references(() => purchaseReceipts.id, { onDelete: "cascade" }), purchaseItemId: text("purchase_item_id").notNull().references(() => purchaseItems.id, { onDelete: "restrict" }), productId: text("product_id").notNull().references(() => products.id, { onDelete: "restrict" }), quantity: integer("quantity").notNull(), unitCost: numeric("unit_cost", { precision: 14, scale: 2 }).notNull(), currency: varchar("currency", { length: 3 }).notNull() }, (table) => ({ receiptProductUnique: uniqueIndex("purchase_receipt_items_product_unique").on(table.receiptId, table.productId), quantityPositive: check("purchase_receipt_items_quantity_positive", sql.raw("quantity > 0")) }));
export const importDocuments = pgTable("import_documents", { id: text("id").primaryKey(), supplierId: text("supplier_id").references(() => suppliers.id, { onDelete: "set null" }), commercialInvoice: text("commercial_invoice"), packingList: text("packing_list"), originCountry: varchar("origin_country", { length: 2 }), currency: varchar("currency", { length: 3 }), fob: numeric("fob", { precision: 14, scale: 2 }), freight: numeric("freight", { precision: 14, scale: 2 }), insurance: numeric("insurance", { precision: 14, scale: 2 }), customs: numeric("customs", { precision: 14, scale: 2 }), taxes: numeric("taxes", { precision: 14, scale: 2 }), otherCosts: numeric("other_costs", { precision: 14, scale: 2 }), landedCost: numeric("landed_cost", { precision: 14, scale: 2 }), metadata: jsonb("metadata").$type<Record<string, unknown> | null>(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
