import assert from "node:assert/strict";
import fs from "node:fs";

const read = (file) => fs.readFileSync(file, "utf8");
const views = read("src/components/admin/AdminCategoryViews.tsx");
const shell = read("src/components/admin/AdminShell.tsx");
const layout = read("src/app/admin/layout.tsx");
const denied = read("src/app/admin/sin-acceso/page.tsx");
const roles = read("src/lib/roles.ts");
const operationsRoute = read("src/app/admin/operaciones/page.tsx");
const home = read("src/components/admin/AdminTanda2Workspaces.tsx");
const account = read("src/app/cuenta/page.tsx");
const accountOverview = read("src/lib/account-overview.ts");

assert.doesNotMatch(views, /25 may\.?\s*-\s*24 jun\.?\s*2024/i);
assert.doesNotMatch(views, /190\.12\.45\.23/);
assert.doesNotMatch(views, /\[156,\s*28,\s*42,\s*71,\s*15\]/);
assert.doesNotMatch(views, /Transferencia bancaria.*Deposito en cuenta.*Tarjeta de credito/i);
assert.match(views, /aria-label|aria-labelledby/);
assert.match(shell, /sticky|lg:sticky/);
assert.doesNotMatch(shell, />12<|2024 ColdPower/);
assert.match(shell, /router\.push/);
assert.match(operationsRoute, /requirePermission\("operations\.view"\)/);
assert.match(operationsRoute, /<OperationsCenter/);
assert.match(home, /Tanda2Home|Tanda2Dashboard/);
assert.match(accountOverview, /isStaffRole/);
assert.match(account, /adminHref/);
assert.match(account, /Ir al panel administrativo/);
assert.match(accountOverview, /\/admin\/dashboard/);
const generalHome = layout.indexOf('section: "General", href: "/admin/inicio"');
const generalDashboard = layout.indexOf('section: "General", href: "/admin/dashboard"');
const commercial = layout.indexOf('section: "Comercial"');
assert.ok(generalHome >= 0 && generalHome < generalDashboard && generalDashboard < commercial, "General must be the first admin section");
assert.doesNotMatch(layout, /section: "Gestión", href: "\/admin\/(inicio|dashboard)"/);
assert.match(shell, /min-h-0 flex-1 overflow-y-auto/);
assert.match(shell, /mt-auto shrink-0/);
assert.match(denied, /title: "Sin acceso \| Panel admin ColdPower"/);
assert.doesNotMatch(denied, /min-h-\[50vh\]/);
assert.match(denied, /mx-auto w-full max-w-2xl/);
assert.match(roles, /ALMACEN: "Almac.n"/);
assert.match(shell, /ALMACEN:[\s\S]*roleLabel\("ALMACEN"\)/);

console.log("cp029-admin-foundation-contract: passed");
