import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
const root=process.cwd();const read=(file)=>readFileSync(join(root,file),"utf8");
test("CP-039 pedidos tienen filtros, métricas, detalle y exportación paginados",()=>{const contract=read("src/lib/orders-contract.ts"),repo=read("src/lib/orders-repository.ts"),route=read("src/app/api/admin/pedidos/route.ts"),detail=read("src/app/api/admin/pedidos/[id]/route.ts"),exportRoute=read("src/app/api/admin/pedidos/export/route.ts");for(const field of ["query","status","customerId","sellerId","locationId","deliveryMethod","paymentStatus","dateFrom","dateTo","page","pageSize","new","preparing","inTransit","delivered","pendingPayment"])assert.match(contract,new RegExp(field));for(const field of ["pendingPayment","preparing","inTransit","delivered","payments","inventoryReservations","orderItems"])assert.match(repo,new RegExp(field));assert.ok(repo.includes("limit(pageSize)"));assert.ok(repo.includes("offset((page - 1) * pageSize)"));assert.match(route,/getOrdersPage/);assert.match(detail,/getOrderDetail/);assert.match(repo,/audit|inventoryReservations/);assert.match(exportRoute,/orders\.exported/);assert.match(exportRoute,/text\/csv/)})
test("CP-039 conserva transición, historial, reserva, pago manual e idempotencia de status",()=>{const service=read("src/lib/sales-service.ts"),validation=read("src/lib/sales-validation.ts"),route=read("src/app/api/admin/pedidos/[id]/route.ts"),schema=read("src/db/sales-schema.ts"),migration=read("drizzle/0041_cp039_order_status_idempotency.sql");assert.match(validation,/canTransitionOrder/);assert.match(service,/orderStatusHistory/);assert.match(service,/releaseInventoryReservationInTransaction/);assert.match(service,/consumeInventoryReservationInTransaction/);assert.match(service,/cancellationReason/);assert.match(service,/ORDER_IDEMPOTENCY_CONFLICT/);assert.match(route,/INVALID_ORDER_STATUS/);assert.match(route,/CANCELLATION_REASON_REQUIRED/);assert.match(route,/Idempotency-Key/);assert.match(schema,/order_status_history_idempotency_unique/);assert.match(migration,/idempotency_key/)})
test("CP-039 registra y resuelve incidencias sin editar stock desde la UI",()=>{const ui=read("src/components/admin/OrdersControlCenter.tsx"),service=read("src/lib/order-fulfillment-service.ts"),route=read("src/app/api/admin/pedidos/[id]/incidencias/route.ts");for(const field of ["STOCK_MISMATCH","orderItemId","blocker","Resolver","resolutionNote"])assert.match(ui,new RegExp(field));assert.match(service,/resolveOrderIncident/);assert.match(service,/orders\.incident_created/);assert.match(service,/orders\.incident_resolved/);assert.match(route,/resolveOrderIncident/)})
test("CP-039 no mezcla monedas en la conciliación de pedidos",()=>{const repo=read("src/lib/orders-repository.ts");assert.match(repo,/eq\(payments\.currency, orders\.currency\)/);assert.match(repo,/eq\(paymentRefunds\.currency, orders\.currency\)/);assert.match(repo,/p2\.currency = \$\{orderCurrencyReference\}/)})
test("CP-039 protege el detalle financiero por permiso y ofrece reintento de carga",()=>{const route=read("src/app/api/admin/pedidos/[id]/route.ts"),repo=read("src/lib/orders-repository.ts"),ui=read("src/components/admin/OrdersControlCenter.tsx");assert.match(route,/includeFinancial: can\(actor\.role, "payments\.view"\)/);assert.match(repo,/options: \{ includeFinancial\?: boolean \}/);assert.match(repo,/if \(!includeFinancial\) return base/);assert.match(ui,/canPaymentsView/);assert.match(ui,/Reintentar/)})
test("CP-039 exporta vendedor, local, pago y atención del pedido",()=>{const route=read("src/app/api/admin/pedidos/export/route.ts");for(const field of ["Vendedor","Local","Pago","Atención"])assert.match(route,new RegExp(field))});
test("CP-039 ofrece loading state estructural para la navegación al módulo",()=>{const loading=read("src/app/admin/pedidos/loading.tsx");assert.match(loading,/aria-busy="true"/);assert.match(loading,/Cargando pedidos/);assert.match(loading,/animate-pulse/);assert.match(loading,/grid/)});
test("CP-039 ofrece error state accionable sin exponer detalles internos",()=>{const error=read("src/app/admin/pedidos/error.tsx"),shared=read("src/components/admin/AdminSegmentError.tsx");assert.match(error,/No pudimos cargar los pedidos/);assert.match(error,/unstable_retry/);assert.match(shared,/role="alert"/);assert.match(shared,/Reintentar/);assert.doesNotMatch(shared,/error\.message/)});
