import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import vm from "node:vm";
import ts from "typescript";

const root = process.cwd();
const require = createRequire(import.meta.url);
const read = (relativePath) => readFileSync(join(root, relativePath), "utf8");
const exists = (relativePath) => existsSync(join(root, relativePath));
const cartLibPath = "src/lib/cart.ts";
assert.equal(exists(cartLibPath), true);
const transpiled = ts.transpileModule(read(cartLibPath), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const testModule = { exports: {} };
vm.runInNewContext(transpiled, { exports: testModule.exports, module: testModule, require }, { filename: cartLibPath });
const { addCartItem, updateCartItemQuantity, removeCartItem, getCartTotalQuantity, buildCartQuoteMessage } = testModule.exports;
let cart = [];
cart = addCartItem(cart, "prod-split-carrier-12000btu");
cart = addCartItem(cart, "prod-split-carrier-12000btu");
cart = addCartItem(cart, "prod-valvula-sporlan", 3);
assert.equal(JSON.stringify(cart), JSON.stringify([{ productId: "prod-split-carrier-12000btu", quantity: 2 }, { productId: "prod-valvula-sporlan", quantity: 3 }]));
assert.equal(getCartTotalQuantity(cart), 5);
cart = updateCartItemQuantity(cart, "prod-valvula-sporlan", -2);
assert.equal(JSON.stringify(cart), JSON.stringify([{ productId: "prod-split-carrier-12000btu", quantity: 2 }]));
cart = removeCartItem(cart, "prod-split-carrier-12000btu");
assert.equal(JSON.stringify(cart), "[]");
const quoteMessage = buildCartQuoteMessage([{ productId: "prod-termostato-itc1000", quantity: 2, name: "Termostato digital universal ITC-1000", sku: "CP-TER-ITC-1000" }]);
assert.match(quoteMessage, /2 x Termostato digital universal ITC-1000/);
assert.match(quoteMessage, /CP-TER-ITC-1000/);

for (const file of ["src/components/cart/CartProvider.tsx", "src/components/cart/CartButton.tsx", "src/components/cart/AddToCartButton.tsx", "src/components/cart/CartQuotePanel.tsx"]) assert.equal(exists(file), true, `${file} should exist`);
const header = read("src/components/layout/Header.tsx");
assert.match(header, /CartButton/);
assert.doesNotMatch(header, /aria-label="Ver cotizaciÃƒÂ³n"[\s\S]*ShoppingBag/);
const productCard = read("src/components/catalog/ProductCard.tsx");
const productDetail = read("src/components/product/ProductDetail.tsx");
const transactionBox = read("src/components/product/TransactionBox.tsx");
const quotePage = read("src/app/cotizacion/page.tsx");
assert.match(productCard, /AddToCartButton/);
assert.match(productDetail, /TransactionBox/);
assert.match(transactionBox, /AddToCartButton/);
assert.match(quotePage, /CartQuotePanel/);
