import type { Metadata } from "next";
import { desc, eq } from "drizzle-orm";
import { requireUser } from "@/lib/auth";
import { getDb } from "@/db";
import { customers } from "@/db/crm-schema";
import { orders, payments } from "@/db/sales-schema";
import { Badge } from "@/components/shared/Badge";

export const metadata: Metadata = { title: "Mis pedidos | ColdPower", description: "Seguimiento de pedidos, reservas y pagos en ColdPower." };
const labels: Record<string, string> = { NEW: "Nuevo", PAYMENT_PENDING: "Pago pendiente", PAID: "Pagado", PREPARING: "En preparación", READY_FOR_PICKUP: "Listo para recoger", SHIPPED: "Enviado", DELIVERED: "Entregado", CANCELLED: "Cancelado" };
export default async function CuentaPedidosPage() {
  const { userId } = await requireUser(); let rows: Array<{ order: typeof orders.$inferSelect; payment: typeof payments.$inferSelect | null }> = [];
  try { rows = await getDb().select({ order: orders, payment: payments }).from(orders).innerJoin(customers, eq(orders.customerId, customers.id)).leftJoin(payments, eq(payments.orderId, orders.id)).where(eq(customers.userId, userId)).orderBy(desc(orders.createdAt)); } catch (error) { console.error("ColdPower: no se pudieron cargar los pedidos del cliente", error); }
  return <section className="bg-background py-14 sm:py-18"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-primary">Mi cuenta</p><h1 className="mt-3 font-display text-3xl font-black text-dark">Mis pedidos</h1><p className="mt-3 text-sm leading-6 text-gray-text">Consulta estado, total, reserva y pago de tus pedidos. Desde el historial puedes repetir una solicitud.</p>{rows.length === 0 ? <div className="mt-8 rounded-md border border-border bg-white p-6"><p className="font-bold text-dark">Todavía no tienes pedidos.</p><p className="mt-2 text-sm leading-6 text-gray-text">Puedes comprar como invitado desde el checkout cuando exista precio y stock confirmados.</p></div> : <div className="mt-8 grid gap-4">{rows.map(({ order, payment }) => <article key={order.id} className="rounded-md border border-border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs font-black text-gray-text">{order.code}</p><h2 className="mt-1 font-display text-xl font-black text-dark">Pedido {order.code}</h2></div><Badge variant={order.status === "CANCELLED" ? "danger" : order.status === "PAID" ? "stock" : "warning"}>{labels[order.status] ?? order.status}</Badge></div><dl className="mt-4 grid gap-3 border-t border-border pt-4 text-sm sm:grid-cols-3"><div><dt className="text-xs font-extrabold uppercase tracking-[0.08em] text-gray-text">Total</dt><dd className="mt-1 font-bold text-dark">{order.currency} {order.total}</dd></div><div><dt className="text-xs font-extrabold uppercase tracking-[0.08em] text-gray-text">Entrega</dt><dd className="mt-1 font-bold text-dark">{order.deliveryMethod}</dd></div><div><dt className="text-xs font-extrabold uppercase tracking-[0.08em] text-gray-text">Pago</dt><dd className="mt-1 font-bold text-dark">{payment?.status ?? "Pendiente"}</dd></div></dl><p className="mt-4 text-xs text-gray-text">Creado: {order.createdAt.toLocaleString("es-PE")}</p><a href="/cuenta/historial" className="mt-3 inline-flex text-xs font-extrabold text-primary hover:underline">Repetir pedido desde historial</a></article>)}</div>}</div></section>;
}
